# Generated by Django 2.0.3 on 2018-03-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.SmallIntegerField(default=0)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluacion.Criterio')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluacion.Equipo')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluacion.Jurado')),
            ],
        ),
    ]
